DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS regions;

CREATE TABLE regions (
  id SERIAL PRIMARY KEY,
  name VARCHAR(30) NOT NULL,
  subdomain VARCHAR(30) UNIQUE NOT NULL
);

CREATE TABLE categories (
  id SERIAL PRIMARY KEY,
  name VARCHAR(30) UNIQUE NOT NULL,
  description TEXT,
  parent_category INT REFERENCES categories ON DELETE CASCADE
);

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(30) UNIQUE NOT NULL,
  password_hash CHAR(72) NOT NULL,
  preferred_region INT REFERENCES regions ON DELETE SET NULL
);

CREATE TABLE posts (
  id SERIAL PRIMARY KEY,
  title VARCHAR(30) NOT NULL,
  text TEXT NOT NULL,
  location VARCHAR(30),
  region INT NOT NULL REFERENCES regions ON DELETE CASCADE,
  category INT NOT NULL REFERENCES categories ON DELETE CASCADE,
  owner INT NOT NULL REFERENCES users ON DELETE CASCADE
);