DROP TABLE IF EXISTS results;
DROP TABLE IF EXISTS goals;
DROP TABLE IF EXISTS lineups;
DROP TABLE IF EXISTS matches;
DROP TABLE IF EXISTS players;
DROP TABLE IF EXISTS referees;
DROP TABLE IF EXISTS positions;
DROP TABLE IF EXISTS teams;
DROP TABLE IF EXISTS seasons;
DROP TABLE IF EXISTS people;

CREATE TABLE people (
  id SERIAL PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30),
  home_town VARCHAR(30) NOT NULL,
  birthdate TIMESTAMP NOT NULL
);

CREATE TABLE seasons (
  id SERIAL PRIMARY KEY,
  name VARCHAR(30) NOT NULL,
  start_date TIMESTAMP NOT NULL,
  end_date TIMESTAMP NOT NULL
);

CREATE TABLE teams (
  id SERIAL PRIMARY KEY,
  name VARCHAR(30) UNIQUE NOT NULL,
  location VARCHAR(30) NOT NULL,
  stadium VARCHAR(30)
);

CREATE TABLE positions (
  id SERIAL PRIMARY KEY,
  name VARCHAR(30) UNIQUE NOT NULL
);

CREATE TABLE referees (
  id SERIAL PRIMARY KEY,
  person INT REFERENCES people ON DELETE CASCADE
);

CREATE TABLE players (
  id SERIAL PRIMARY KEY,
  person INT NOT NULL REFERENCES people ON DELETE CASCADE,
  team INT REFERENCES teams ON DELETE SET NULL,
  position INT REFERENCES positions ON DELETE SET NULL
);

CREATE TABLE matches (
  id SERIAL PRIMARY KEY,
  gametime TIMESTAMP NOT NULL,
  name VARCHAR(50), -- league semifinal, Chicken Bowl, etc.
  status VARCHAR(30) NOT NULL DEFAULT 'future', -- ongoing, completed, postponed, etc.
  referee INT NOT NULL REFERENCES referees ON DELETE SET NULL,
  season INT NOT NULL REFERENCES seasons ON DELETE CASCADE,
  away_team INT NOT NULL REFERENCES teams ON DELETE CASCADE,
  home_team INT NOT NULL REFERENCES teams ON DELETE CASCADE
);

CREATE TABLE lineups (
  id SERIAL PRIMARY KEY,
  position INT NOT NULL REFERENCES positions ON DELETE SET NULL,
  match INT NOT NULL REFERENCES matches ON DELETE CASCADE,
  player INT NOT NULL REFERENCES players ON DELETE SET NULL,
  team INT NOT NULL REFERENCES teams ON DELETE SET NULL
);

CREATE TABLE goals (
  id SERIAL PRIMARY KEY,
  game_minutes INT NOT NULL,
  match INT NOT NULL REFERENCES matches ON DELETE CASCADE,
  lineup_position INT NOT NULL REFERENCES lineups ON DELETE CASCADE
);

CREATE TABLE results (
  id SERIAL PRIMARY KEY,
  match INT NOT NULL REFERENCES matches ON DELETE CASCADE,
  winning_team INT NOT NULL REFERENCES teams ON DELETE SET NULL,
  away_score INT NOT NULL,
  home_score INT NOT NULL
);