SQLALCHEMY_DATABASE_URI = 'postgresql:///feedback_test'
SQLALCHEMY_ECHO = false
TESTING = true # Have Flask return real errors w/o HTML
WTF_CSRF_ENABLED = false
SECRET_KEY = 'FlaskDebugTB-Key-751xyi'
DEBUG_TB_HOSTS = ["dont-show-debug-toolbar"]